// Deliverable → Markdown — CADENCE-BUILD-SPEC.md §12.3
//
// OWNER: Person D.
//
// What Maya pastes into Notion. Provenance survives the export: every sentence
// that carries evidence gets a footnote marker, and the sources section prints
// the verbatim quote and the URL it came from. An export that drops the receipts
// is the same trap as a chat window.

import type { Deliverable, Evidence, PriceComparison } from "@/lib/contracts";
import type { RunResult } from "@/lib/pipeline-client";

function formatWhen(iso: string): string {
  const d = new Date(iso);
  return Number.isNaN(d.getTime())
    ? iso
    : d.toLocaleString("en-US", {
        month: "short",
        day: "numeric",
        year: "numeric",
        hour: "numeric",
        minute: "2-digit",
      });
}

function priceLine(c: PriceComparison): string {
  const ours =
    c.normalized_monthly_per_seat_ours === null
      ? "not published"
      : `$${c.normalized_monthly_per_seat_ours}/seat/mo`;
  const theirs =
    c.normalized_monthly_per_seat_theirs === null
      ? "not published"
      : `$${c.normalized_monthly_per_seat_theirs}/seat/mo`;
  const verdict =
    c.cheaper === "unknown"
      ? "**No comparison possible**"
      : c.cheaper === "equal"
        ? "Equal"
        : c.cheaper === "ours"
          ? `We are cheaper${c.delta_pct === null ? "" : ` by ${Math.abs(c.delta_pct)}%`}`
          : `They are cheaper${c.delta_pct === null ? "" : ` by ${Math.abs(c.delta_pct)}%`}`;
  return `| ${c.our_tier} | ${ours} | ${c.their_tier} | ${theirs} | ${verdict} | ${c.caveat ?? "—"} |`;
}

export function toMarkdown(run: RunResult): string {
  const d: Deliverable = run.deliverable;
  const evidenceById = new Map(run.evidence.map((e) => [e.id, e]));
  const cited: string[] = [];

  const cite = (ids: string[]): string => {
    const marks = ids
      .filter((id) => evidenceById.has(id))
      .map((id) => {
        if (!cited.includes(id)) cited.push(id);
        return `[^${id}]`;
      });
    return marks.length ? ` ${marks.join("")}` : " **[unsourced]**";
  };

  const flagsBySentence = new Map<string, typeof d.risk_flags>();
  for (const f of d.risk_flags) {
    flagsBySentence.set(f.sentence_id, [...(flagsBySentence.get(f.sentence_id) ?? []), f]);
  }

  const out: string[] = [];
  out.push(`# ${d.title}`, "");
  out.push(`**${d.subject_label}**`, "");
  out.push(
    `Generated ${formatWhen(d.generated_at)} · ${d.word_count} words · ` +
      `${run.source === "cached" ? "cached run" : "live run"}`,
    "",
  );

  for (const section of d.sections) {
    out.push(`## ${section.title}`, "");
    for (const s of section.sentences) {
      const flags = flagsBySentence.get(s.id) ?? [];
      const marker = flags.length
        ? ` ⚑ *${flags.map((f) => f.category.replace(/_/g, " ")).join(", ")}*`
        : "";
      out.push(`- ${s.text}${cite(s.evidence_ids)}${marker}`);
    }
    out.push("");
  }

  if (d.price_comparisons.length) {
    out.push("## Pricing — computed, not written", "");
    out.push("| Our tier | Ours | Their tier | Theirs | Verdict | Caveat |");
    out.push("| --- | --- | --- | --- | --- | --- |");
    for (const c of d.price_comparisons) out.push(priceLine(c));
    out.push("");
  }

  const material = d.feature_matrix.filter((r) => r.matters_to_target);
  if (material.length) {
    out.push("## What matters for this prospect", "");
    out.push("| Feature | Us | Them | Why it matters |");
    out.push("| --- | --- | --- | --- |");
    for (const r of material) out.push(`| ${r.feature} | ${r.ours} | ${r.theirs} | ${r.why} |`);
    out.push("");
  }

  if (d.risk_flags.length) {
    out.push("## Review before you say any of this", "");
    for (const f of d.risk_flags) {
      out.push(
        `- **${f.category.replace(/_/g, " ")}** (${f.severity}) — “${f.span}”  `,
        `  ${f.why}  `,
        `  *Safer:* ${f.suggested_alternative}`,
      );
    }
    out.push("");
  }

  if (d.grounding_issues.length) {
    out.push("## Grounding", "");
    for (const g of d.grounding_issues) {
      out.push(`- **${g.issue.replace(/_/g, " ")}** — ${g.detail}`);
    }
    out.push("");
  }

  if (cited.length) {
    out.push("## Sources", "");
    for (const id of cited) {
      const e = evidenceById.get(id);
      if (!e) continue;
      const where = e.source_url ? `[${e.source_label}](${e.source_url})` : e.source_label;
      const when = e.fetched_at ? ` · fetched ${formatWhen(e.fetched_at)}` : "";
      out.push(`[^${id}]: “${e.quote}” — ${where}${when}`);
    }
    out.push("");
  }

  out.push("---", "");
  out.push(
    "Generated by Cadence. Maya Okonkwo and Thicket are synthetic and created for " +
      "demonstration; competitor and prospect pages are real public marketing pages. " +
      "Every claim above traces to a quoted source or is marked unsourced.",
  );

  return out.join("\n");
}

/** A short mail body. mailto: URLs get truncated by clients, so this is the gist, not the card. */
export function toMailBody(run: RunResult): string {
  const d = run.deliverable;
  const pivots = d.sections.find((s) => s.key === "pivots");
  const lines: string[] = [`${d.subject_label}`, ""];

  if (pivots) {
    lines.push(`${pivots.title}:`);
    for (const s of pivots.sentences.slice(0, 3)) lines.push(`• ${s.text}`);
    lines.push("");
  }

  const unresolved = d.risk_flags.filter((f) => f.status === "pending");
  if (unresolved.length) {
    lines.push(`${unresolved.length} claim(s) still flagged for review — do not send as final.`);
    lines.push("");
  }

  lines.push("Full card with sources attached from Cadence.");
  lines.push("Synthetic demo data. Cadence did not send this message — your mail client did.");
  return lines.join("\n");
}

/** Resolve the evidence behind a sentence, for the print sheet. */
export function evidenceFor(ids: string[], evidence: Evidence[]): Evidence[] {
  const byId = new Map(evidence.map((e) => [e.id, e]));
  return ids.map((id) => byId.get(id)).filter((e): e is Evidence => Boolean(e));
}
