// Cadence data contracts — CADENCE-BUILD-SPEC.md §7
//
// OWNER: Person A, exclusively. Frozen at 1:05.
// Need a field? Message A in chat. Do not edit this file yourself.
//
// Pre-seeded from the spec by Person D during repo setup so nobody is blocked.
// Person A: review, correct, and announce the freeze.

import { z } from "zod";

export const Recipe = z.enum(["battlecard", "investor_update"]);

/** One atomic fact, from anywhere, with a verbatim receipt. Shared by both recipes. */
export const Evidence = z.object({
  id: z.string(),                       // "ev_001"
  recipe_role: z.enum(["target", "competitor", "own", "founder_input"]),
  source: z.enum(["url", "paste", "slack", "csv", "interview"]),
  source_label: z.string(),             // "acmevet.com/pricing" | "Slack #general Mar 12"
  source_url: z.string().nullable(),
  quote: z.string(),                    // VERBATIM span. Never paraphrase into this field.
  summary: z.string(),                  // one clause
  type: z.enum([
    "pricing", "feature", "positioning", "proof_point", "segment", "integration",
    "metric", "win", "loss", "risk", "ask", "admin",
  ]),
  entities: z.array(z.string()),
  confidence: z.number().min(0).max(1),
  fetched_at: z.string().nullable(),    // ISO — staleness matters for competitor pages
});

export const PriceTier = z.object({
  company: z.string(),
  tier_name: z.string(),
  price_amount: z.number().nullable(),  // null = "Contact us"
  price_unit: z.enum([
    "per_seat_month", "per_seat_year", "flat_month", "flat_year", "usage", "unknown",
  ]),
  seat_minimum: z.number().nullable(),
  included_features: z.array(z.string()),
  evidence_ids: z.array(z.string()),
});

/** Every field below is computed in TypeScript. The model never fills these. */
export const PriceComparison = z.object({
  our_tier: z.string(),
  their_tier: z.string(),
  normalized_monthly_per_seat_ours: z.number().nullable(),
  normalized_monthly_per_seat_theirs: z.number().nullable(),
  delta_abs: z.number().nullable(),
  delta_pct: z.number().nullable(),
  cheaper: z.enum(["ours", "theirs", "equal", "unknown"]),
  caveat: z.string().nullable(),        // "their pricing is quote-only above 10 seats"
});

export const FeatureRow = z.object({
  feature: z.string(),
  ours: z.enum(["yes", "no", "partial", "unknown"]),
  theirs: z.enum(["yes", "no", "partial", "unknown"]),
  matters_to_target: z.boolean(),
  why: z.string(),
  evidence_ids: z.array(z.string()),
});

export const Differentiator = z.object({
  id: z.string(),
  claim: z.string(),
  direction: z.enum(["we_win", "they_win", "parity"]),
  materiality: z.number().int().min(1).max(5),
  materiality_reason: z.string(),
  evidence_ids: z.array(z.string()),
});

export const Sentence = z.object({
  id: z.string(),
  text: z.string(),
  evidence_ids: z.array(z.string()),    // [] → grounding flag
});

export const Section = z.object({
  // battlecard: positioning | pricing | we_win | they_win | pivots | questions
  // investor update: headline | metrics | highlights | lowlights | asks
  key: z.string(),
  title: z.string(),
  sentences: z.array(Sentence),
});

export const RiskFlag = z.object({
  id: z.string(),
  sentence_id: z.string(),
  span: z.string(),                     // exact substring to highlight
  category: z.enum([
    // battlecard
    "unverified_competitor_claim", "disparagement", "stale_pricing",
    "absolute_superiority_claim", "confidential_pricing",
    // investor update
    "unannounced_fundraise", "named_churned_customer", "personnel_detail",
    "legal_exposure", "unverified_forward_claim",
  ]),
  severity: z.enum(["low", "medium", "high"]),
  why: z.string(),
  suggested_alternative: z.string(),    // pre-written safe phrasing
  status: z.enum(["pending", "approved", "redacted"]).default("pending"),
});

export const GroundingIssue = z.object({
  sentence_id: z.string(),
  issue: z.enum(["unsourced", "number_not_in_table", "overstated", "stale_evidence"]),
  detail: z.string(),
});

export const Deliverable = z.object({
  recipe: Recipe,
  title: z.string(),
  subject_label: z.string(),            // "Thicket vs. VetFlow — for Brookside Animal Hospital"
  sections: z.array(Section),
  price_comparisons: z.array(PriceComparison),
  feature_matrix: z.array(FeatureRow),
  risk_flags: z.array(RiskFlag),
  grounding_issues: z.array(GroundingIssue),
  generated_at: z.string(),
  word_count: z.number(),
});

// Inferred types — import these rather than redeclaring shapes.
export type Recipe = z.infer<typeof Recipe>;
export type Evidence = z.infer<typeof Evidence>;
export type PriceTier = z.infer<typeof PriceTier>;
export type PriceComparison = z.infer<typeof PriceComparison>;
export type FeatureRow = z.infer<typeof FeatureRow>;
export type Differentiator = z.infer<typeof Differentiator>;
export type Sentence = z.infer<typeof Sentence>;
export type Section = z.infer<typeof Section>;
export type RiskFlag = z.infer<typeof RiskFlag>;
export type GroundingIssue = z.infer<typeof GroundingIssue>;
export type Deliverable = z.infer<typeof Deliverable>;

// Array schemas — model responses are usually arrays; validate with these.
export const EvidenceArray = z.array(Evidence);
export const PriceTierArray = z.array(PriceTier);
export const FeatureRowArray = z.array(FeatureRow);
export const DifferentiatorArray = z.array(Differentiator);
export const RiskFlagArray = z.array(RiskFlag);
export const GroundingIssueArray = z.array(GroundingIssue);
